exports.RESET_PASSWORD_CODE_DURATION_MINUTES = 5;
exports.ACCESS_TOKEN_LIFETIME_DURATION_MINUTES = 60;
exports.REFRESH_TOKEN_LIFETIME_DURATION_MINUTES = 60 * 24 * 30;
exports.LIMIT_ITEMS_IN_LIST = 3000;
